[versions]
activityVersion = "1.6.0"
agp = "8.11.1"
androidDatabaseSqlcipher = "4.6.0"
androidxJunit = "1.1.5"
androidxRoomRuntime = "2.5.2"
core = "1.16.0"
coreVersion = "1.7.0"
espressoCoreVersion = "3.5.1"
jsch = "0.1.55"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
lifecycleViewmodel = "2.9.2"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
mockitoCore = "5.20.0"
okhttp = "5.3.0"
orgEclipseJgit = "6.7.0.202309050840-r"
roomCompiler = "2.7.2"
roomCommonJvm = "2.7.2"
androidxJunitVersion = "1.3.0"
androidxEspressoCore = "3.7.0"
roomCompilerVersion = "2.5.2"
sqliteFramework = "2.6.1"

[libraries]
activity-v160 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
android-database-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "androidDatabaseSqlcipher" }
androidx-room-compiler-v252 = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
androidx-room-runtime-v252 = { module = "androidx.room:room-runtime", version.ref = "androidxRoomRuntime" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqliteFramework" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqliteFramework" }
core = { module = "androidx.core:core", version.ref = "core" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "espressoCoreVersion" }
jsch = { module = "com.jcraft:jsch", version.ref = "jsch" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
rules = { module = "androidx.test:rules", version.ref = "coreVersion" }
runner = { module = "androidx.test:runner", version.ref = "coreVersion" }
test-core = { module = "androidx.test:core", version.ref = "coreVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

